### ISSUE TITLE
Error while starting sa-frontend 

### ISSUE THREAD

**Issue by smaillns** [rinormaloku/k8s-mastery#16]
After downloading dependencies, I've executed `npm start` .. the following  errors appear `const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! salogic-front@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the salogic-front@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the salogic-front package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs salogic-front
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls salogic-front
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/slounes/Bureau/minikube_test/k8s-mastery/sa-frontend/npm-debug.log
`

**Comment by smaillns** [comment]
It's Ok now, I just need to upgrade my node to the latest version [https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version/55686671#55686671](url)
