### ISSUE TITLE
npm start throwing the below error 

### ISSUE THREAD

**Issue by ywauto83** [rinormaloku/k8s-mastery#9]
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by ywauto83** [comment]
closing. sorry, my nodejs and npm versions are out-of-dated
